/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mfreyre' at '8/4/15 1:55 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/4/15 1:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
