import java.io.PrintStream;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mfreyre' at '8/4/15 1:55 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/4/15 1:55 PM
 */
public class Library {
    private PrintStream printStream;
    private List<String> libraryBooks;

    public Library(PrintStream printStream, List<String> libraryBooksForTest) {
        this.printStream = printStream;
        this.libraryBooks = libraryBooksForTest;
    }

    public void hello() {
        printStream.println("Welcome to the Library.");
    }

    public void printAllLibraryBooks() {
        for (String book : libraryBooks) {
            printStream.println(book);
        }
    }
}
