import org.junit.Test;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mfreyre' at '8/4/15 1:55 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/4/15 1:55 PM
 */
public class LibraryTest {
    @Test public void testPrintsWelcomeUponOpening() {
        List<String> libraryBooksForTest = new ArrayList<>();
        libraryBooksForTest.add("Pat's Journal");
        libraryBooksForTest.add("Mariel's Secrets");
        PrintStream printStream = mock(PrintStream.class);
        Library classUnderTest = new Library(printStream, libraryBooksForTest);
        classUnderTest.hello();
        verify(printStream).println("Welcome to the Library.");

    }

    @Test
    public void testAllLibraryBooksGetListed() {
        List<String> libraryBooksForTest = new ArrayList<>();
        libraryBooksForTest.add("Pat's Journal");
        libraryBooksForTest.add("Mariel's Secrets");
        PrintStream printStream = mock(PrintStream.class);
        Library classUnderTest = new Library(printStream, libraryBooksForTest);

        classUnderTest.printAllLibraryBooks();

        verify(printStream).println("Pat's Journal");
        verify(printStream).println("Mariel's Secrets");
    }
}
