import org.junit.Before;
import org.junit.Test;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;


import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mfreyre' at '8/4/15 1:55 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/4/15 1:55 PM
 */
public class LibraryTest {

    private List<String> libraryBooksForTest;
    private PrintStream printStream;
    private Library classUnderTest;

    @Before
    public void setUp() throws Exception {
        libraryBooksForTest = new ArrayList<>();
        libraryBooksForTest.add("Pat's Journal");
        libraryBooksForTest.add("Mariel's Secrets");
        printStream = mock(PrintStream.class);
        classUnderTest = new Library(printStream, libraryBooksForTest);
    }

    @Test public void testPrintsWelcomeUponOpening() {

        classUnderTest.hello();
        verify(printStream).println("Welcome to the Library.");

    }

    @Test
    public void testAllLibraryBooksGetListed() {

        classUnderTest.printAllLibraryBooks();

        verify(printStream).println("Pat's Journal");
        verify(printStream).println("Mariel's Secrets");
    }

    @Test
    public void testPrintsMessageWhenNoBooksInLibrary()  {

    }
}
