import org.junit.Test;
import java.io.PrintStream;

import static org.mockito.Matchers.contains;
import static org.mockito.Mockito.*;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mfreyre' at '8/4/15 1:55 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/4/15 1:55 PM
 */
public class WelcomeMessageTest {
    @Test public void testPrintsWelcomeUponOpening() {

        PrintStream printStream = mock(PrintStream.class);
        Library classUnderTest = new Library(printStream);
        classUnderTest.hello();
        verify(printStream).println("Welcome to the Library.");

    }
}
